const TRAINING_RULES = [
  {
    id: "nr06-epi",
    title: "Uso, guarda e conservação de EPI - NR-06",
    reason: "Sugerido quando houver EPI aplicável ao risco informado.",
    requiresEpi: true,
  },
  {
    id: "nr10-electricity",
    title: "Segurança em instalações e serviços em eletricidade - NR-10",
    reason: "Sugerido para exposição a choque elétrico, painéis, equipamentos energizados ou serviços elétricos.",
    riskCodes: ["ACI.003"],
    keywords: ["eletric", "energiz", "painel", "quadro", "cabine primaria", "alta tensao", "baixa tensao"],
  },
  {
    id: "nr11-material-handling",
    title: "Transporte, movimentação, armazenagem e manuseio de materiais - NR-11",
    reason: "Sugerido para operação de empilhadeira, movimentação de cargas, veículos/equipamentos móveis e armazenagem.",
    riskCodes: ["ACI.008", "ACI.014"],
    keywords: ["empilhadeira", "ponte rolante", "talha", "guindaste", "paleteira", "movimentacao de carga", "armazenagem", "carga"],
    cnaePrefixes: ["49", "52"],
  },
  {
    id: "nr12-machines",
    title: "Segurança no trabalho em máquinas e equipamentos - NR-12",
    reason: "Sugerido para operação, limpeza, manutenção ou intervenção em máquinas e equipamentos.",
    riskCodes: ["ACI.005", "ACI.006", "ACI.007", "ACI.012"],
    keywords: ["maquina", "equipamento", "prensa", "serra", "torno", "injetora", "esteira", "partes moveis"],
  },
  {
    id: "nr17-ergonomics",
    title: "Orientação ergonômica - NR-17",
    reason: "Sugerido para riscos ergonômicos, organização do trabalho, postura, repetitividade e mobiliário.",
    riskGroups: ["Ergonômicos"],
    keywords: ["headset", "computador", "digitacao", "postura", "mobiliario", "repetitividade"],
  },
  {
    id: "nr18-construction",
    title: "Condições de segurança e saúde na indústria da construção - NR-18",
    reason: "Sugerido para atividades de construção, obra, demolição, reforma e frentes de trabalho similares.",
    keywords: ["obra", "construcao", "demolicao", "reforma", "canteiro"],
    cnaePrefixes: ["41", "42", "43"],
  },
  {
    id: "nr20-flammables",
    title: "Segurança e saúde no trabalho com inflamáveis e combustíveis - NR-20",
    reason: "Sugerido para inflamáveis, combustíveis, GLP, abastecimento, armazenamento ou risco de incêndio/explosão.",
    riskCodes: ["ACI.009", "ACI.010"],
    keywords: ["inflamavel", "combustivel", "glp", "gas", "abastecimento", "tanque", "solvente", "explosao"],
  },
  {
    id: "nr23-fire",
    title: "Prevenção e combate a incêndio / abandono de área - NR-23",
    reason: "Sugerido quando houver risco de incêndio, explosão, evacuação ou uso de equipamentos de combate a incêndio.",
    riskCodes: ["ACI.009"],
    keywords: ["incendio", "explosao", "extintor", "rota de fuga", "evacuacao"],
  },
  {
    id: "nr31-rural",
    title: "Segurança e saúde no trabalho rural - NR-31",
    reason: "Sugerido para atividades de agricultura, pecuária, silvicultura, exploração florestal e aquicultura.",
    keywords: ["agricultura", "pecuaria", "rural", "fazenda", "silvicultura", "florestal", "aquicultura"],
    cnaePrefixes: ["01", "02", "03"],
  },
  {
    id: "nr32-healthcare",
    title: "Segurança e saúde no trabalho em serviços de saúde - NR-32",
    reason: "Sugerido para serviços de saúde, contato com pacientes, materiais biológicos, perfurocortantes e resíduos de saúde.",
    riskGroups: ["Biológicos"],
    keywords: ["paciente", "hospital", "clinica", "laboratorio", "perfurocortante", "material biologico", "residuo de saude"],
    cnaePrefixes: ["86", "87", "88"],
  },
  {
    id: "nr33-confined-space",
    title: "Segurança e saúde nos trabalhos em espaços confinados - NR-33",
    reason: "Sugerido para entrada, permanência, supervisão ou resgate em espaços confinados.",
    riskCodes: ["ACI.015"],
    keywords: ["espaco confinado", "tanque", "silo", "galeria", "biodigestor", "poco", "tubulacao"],
  },
  {
    id: "nr35-height",
    title: "Trabalho em altura - NR-35",
    reason: "Sugerido para atividades com risco de queda de altura, acesso por escada, plataforma, telhado ou estrutura elevada.",
    riskCodes: ["ACI.002"],
    keywords: ["altura", "telhado", "escada", "plataforma", "andaime", "mezanino", "linha de vida"],
  },
  {
    id: "nr36-meat",
    title: "Segurança e saúde no trabalho em empresas de abate e processamento de carnes - NR-36",
    reason: "Sugerido para abate e processamento de carnes e derivados.",
    keywords: ["abate", "frigorifico", "carne", "aves", "suinos", "bovinos"],
    cnaePrefixes: ["101"],
  },
];

