import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../script.js',import.meta.url),'utf8');const table=fs.readFileSync(new URL('../esocial-risk-table.js',import.meta.url),'utf8');
const ctx=vm.createContext({});vm.runInContext(table+';const occupationalRiskSource=ESOCIAL_RISK_TABLE_24;const selectedRisksByTarget=new Map();'+source.slice(source.indexOf('function toggleRiskSelection('),source.indexOf('function createTargetId('))+';globalThis.api={toggleRiskSelection,getSelectedRiskCodes};globalThis.rows=ESOCIAL_RISK_TABLE_24;',ctx);
test('tabela oficial completa com seis grupos e códigos únicos',()=>{assert.equal(ctx.rows.length,92);assert.equal(new Set(ctx.rows.map(r=>r.code)).size,92);assert.equal(new Set(ctx.rows.map(r=>r.group)).size,6);assert.ok(ctx.rows.every(r=>/^\d{2}\.\d{2}\.\d{3}$/.test(r.code)));});
test('ausência substitui agentes somente no mesmo alvo',()=>{const a=ctx.api;a.toggleRiskSelection('a','02.01.001',true);a.toggleRiskSelection('b','01.01.001',true);a.toggleRiskSelection('a','09.01.001',true);assert.deepEqual([...a.getSelectedRiskCodes('a')],['09.01.001']);assert.deepEqual([...a.getSelectedRiskCodes('b')],['01.01.001']);a.toggleRiskSelection('a','03.01.001',true);assert.deepEqual([...a.getSelectedRiskCodes('a')],['03.01.001']);a.toggleRiskSelection('a','ERG.001',true);assert.equal(a.getSelectedRiskCodes('a').size,1);});

test('ausência do eSocial convive com riscos complementares sem permitir mistura de agentes oficiais',()=>{
 const c=vm.createContext({});const extra=fs.readFileSync(new URL('../occupational-risk-table.js',import.meta.url),'utf8');
 vm.runInContext(table+extra+';const occupationalRiskSource=[...ESOCIAL_RISK_TABLE_24,...OCCUPATIONAL_RISK_TABLE];const selectedRisksByTarget=new Map();'+source.slice(source.indexOf('function toggleRiskSelection('),source.indexOf('function createTargetId('))+';globalThis.api={toggleRiskSelection,getSelectedRiskCodes};globalThis.extra=OCCUPATIONAL_RISK_TABLE;',c);
 const a=c.api;a.toggleRiskSelection('cargo','ERG.001',true);a.toggleRiskSelection('cargo','02.01.001',true);a.toggleRiskSelection('cargo','09.01.001',true);assert.deepEqual([...a.getSelectedRiskCodes('cargo')],['ERG.001','09.01.001']);a.toggleRiskSelection('cargo','PSI.001',true);assert.ok(a.getSelectedRiskCodes('cargo').has('09.01.001'));a.toggleRiskSelection('cargo','01.01.001',true);assert.ok(!a.getSelectedRiskCodes('cargo').has('09.01.001'));assert.ok(a.getSelectedRiskCodes('cargo').has('PSI.001'));assert.equal(c.extra.length,38);assert.equal(new Set(c.extra.map(r=>r.code)).size,38);
});

test('controle sanitário tem identificação própria, sem código oficial',()=>{const c=vm.createContext({});vm.runInContext(fs.readFileSync(new URL('../occupational-risk-table.js',import.meta.url),'utf8')+';globalThis.item=OCCUPATIONAL_RISK_TABLE.find(r=>r.code==="SAN.001");',c);assert.equal(c.item.group,'Biológicos');assert.equal(c.item.name,'Contaminação microbiológica dos alimentos pelo manipulador');assert.ok(source.includes('item.risk.code !== "SAN.001"'));});
