import test from 'node:test';import assert from 'node:assert/strict';import {detailTargets,detailAnswers} from '../risk-detail-data.js';
test('separa cargos homônimos por setor e seleciona apenas riscos próprios',()=>{const a={selectedRiskMode:'job',selectedSectors:['A','B'],jobsBySector:[['A',[{name:'Auxiliar',quantity:1}]],['B',[{name:'Auxiliar',quantity:2}]]],selectedRisksByTarget:[['job__a__auxiliar',['x']],['job__b__auxiliar',['y']]]};const t=detailTargets(a,[{code:'x'},{code:'y'}]);assert.equal(t[0].risks[0].code,'x');assert.equal(t[1].risks[0].code,'y');assert.notEqual(t[0].id,t[1].id)});
test('GHE usa identificador salvo e preserva detalhes e outras respostas',()=>{const a={employees:8,selectedRiskMode:'ghe',gheList:[{id:'ghe__a',name:'A',linkedJobs:[]}],selectedRisksByTarget:[['ghe__a',['x','09.01.001']]]};assert.equal(detailTargets(a,[{code:'x'},{code:'09.01.001'}])[0].risks.length,1);const d=new Map([['source__ghe__a__x',{source:'Máquina',frequency:'Diária',note:'Anterior'}]]);const saved=detailAnswers(a,d);assert.equal(saved.employees,8);assert.equal(saved.riskSourcesBySelection[0][1].note,'Anterior');assert.equal(a.riskSourcesBySelection,undefined)});
import vm from 'node:vm';import fs from 'node:fs';
test('último risco volta só após salvar; erro mantém a página',async()=>{
 const s=fs.readFileSync(new URL('../risk-detail.js',import.meta.url),'utf8');const start=s.indexOf("$('#next').onclick=");const end=s.indexOf("$('#back').onclick",start);
 for(const success of [false,true]){const button={};let navigated=false;const ctx=vm.createContext({$:()=>button,saving:false,targets:[{risks:[{}]}],current:0,index:0,persistDetails:async()=>success,location:{assign:()=>{navigated=true}},id:'draft',render:()=>{}});vm.runInContext(s.slice(start,end),ctx);await button.onclick();assert.equal(navigated,success);}
});
test('risco intermediário avança sem salvar ou voltar',async()=>{const s=fs.readFileSync(new URL('../risk-detail.js',import.meta.url),'utf8');const button={};const ctx=vm.createContext({$:()=>button,saving:false,targets:[{risks:[{},{}]}],current:0,index:0,persistDetails:()=>{throw Error('não deve salvar')},location:{assign:()=>{throw Error('não deve navegar')}},render:()=>{}});vm.runInContext(s.slice(s.indexOf("$('#next').onclick="),s.indexOf("$('#back').onclick")),ctx);await button.onclick();assert.equal(ctx.index,1)});
test('último risco de um alvo avança ao próximo com riscos e atualiza o seletor',async()=>{const s=fs.readFileSync(new URL('../risk-detail.js',import.meta.url),'utf8');const button={},select={};const details=new Map([['primeiro',{source:'Texto preservado'}]]);const ctx=vm.createContext({$:id=>id==='#next'?button:select,saving:false,targets:[{risks:[{},{}]},{risks:[]},{risks:[{}]}],current:0,index:1,details,persistDetails:()=>{throw Error('não deve salvar ao trocar alvo')},location:{assign:()=>{throw Error('não deve sair')}},render:()=>{}});vm.runInContext(s.slice(s.indexOf("$('#next').onclick="),s.indexOf("$('#back').onclick")),ctx);await button.onclick();assert.equal(ctx.current,2);assert.equal(ctx.index,0);assert.equal(select.value,'2');assert.equal(details.get('primeiro').source,'Texto preservado');});
test('salva EPIs por risco preservando campos antigos e demais respostas',()=>{const answers={employees:12,epiBySelection:[['old',{applicable:'Sim',items:['Luva']}]],riskSourcesBySelection:[]};const epis=new Map(answers.epiBySelection);epis.set('new',{applicable:'Sim',items:['Protetor auditivo']});const saved=detailAnswers(answers,new Map([['source',{source:'Máquina'}]]),epis);assert.equal(saved.employees,12);assert.deepEqual(saved.epiBySelection[0],answers.epiBySelection[0]);assert.equal(saved.epiBySelection.length,2);assert.equal(answers.epiBySelection.length,1);});
